site_name: ForkToMouth
site_url: https://forktomouth.jburt.me/
repo_name: alphabet5/ForkToMouth
repo_url: https://github.com/alphabet5/ForkToMouth

markdown_extensions:
  - codehilite

theme:
  name: material
  features:
      - tabs
use_directory_urls: false

plugins:
  - search
  - rss

nav:
  - Overview: index.md
  - Recipes By Index:
    - 2020-12.01 Garlic Chiclets: recipes/2020-12.01-chiclets.md
    - 2020-12.02 Smoked Venison Steak: recipes/2020-12.02-smoked-steak.md
    - 2020-12.03 Cranberry Venison Roast: recipes/2020-12.03-cranberry-roast.md
    - 2020-12.04 Pulled Venison: recipes/2020-12.04-pulled-venison.md
    - 2020-12.05 Venison Ribs: recipes/2020-12.05-venison-ribs.md
    - 2020-12.06 Venison Ramen: recipes/2020-12.06-venison-ramen.md
    - 2020-12.07 venison Burgers: recipes/2020-12.07-venison-burgers.md
